edited zero-day-mitigation-guide and zero-day-update
lunasec-io/lunasec pull request #387
Opened 2021-12-26 19:08 UTC by aniratepanda

Line 106 of zero-day-update is a sentence fragment.  I don't know enough about the vulnerability to rewrite it, but it may or may not need revision, at the very least it looked unclear. 

"Now, instead of directly logging the attacker controlled input as with the previous vulnerability like this:"   

"instead of" implies that there will be an alternative presented.   Is it presented in the next paragraph?  I could not tell.

2021-12-27 20:47 UTC, factoidforrest requested changes
Nice catches all around Dana!  These articles continue to need work, they got messy as we were keeping things current and working around the clock.  

I requested a few changes to your changes and also pointed out a few screwed up things in the article that have nothing to do with you, that you could change if you agree.  

Thank you!

2021-12-27 20:47 UTC, factoidforrest commented on docs/blog/2021-12-12-log4j-zero-day-mitigation-guide.mdx
> +been peer-reviewed by multiple security experts, and where possible our sources will be linked from other Security
"linked FOR other security professionals to verify"

2021-12-27 20:47 UTC, factoidforrest commented on docs/blog/2021-12-12-log4j-zero-day-mitigation-guide.mdx
> +been peer-reviewed by multiple security experts, and where possible our sources will be linked from other Security
the "against" is weird though, we can take that out

2021-12-27 20:47 UTC, factoidforrest commented on docs/blog/2021-12-12-log4j-zero-day-mitigation-guide.mdx
> +This vulnerability affects anybody who's using the log4j packages. That means that
"that means primarily java...."

2021-12-27 20:47 UTC, factoidforrest commented on docs/blog/2021-12-12-log4j-zero-day-mitigation-guide.mdx
> +The source code for all of this is available on our GitHub
ehhh.. "The source code for this tool is available..."

2021-12-27 20:47 UTC, factoidforrest commented on docs/blog/2021-12-12-log4j-zero-day-mitigation-guide.mdx
> +If you have updated Log4j to version `2.16.0`, a vulnerability for a Denial of Service (DOS) attack is still present in [certain logging circumstances](https://logging.apache.org/log4j/2.x/security.h
very nice!

2021-12-27 20:47 UTC, factoidforrest commented on docs/blog/2021-12-12-log4j-zero-day-mitigation-guide.mdx
> +- **[Overview (when to use the exploit)](https://www.lunasec.io/docs/blog/log4shell-live-patch/)**
This was correct before. This whole block is really confusing though.
Instead of "We've published articles about this exploit that you can use to learn more about how it works."
it Should say

"We have built a live-patching tool and a hosted live-patching server to make this easy.  Please see [our post] about these tools to learn more."

2021-12-27 20:47 UTC, factoidforrest commented on docs/blog/2021-12-12-log4j-zero-day-mitigation-guide.mdx
> +(above), and is also designed to be implemented at [multiple levels](https://www.lunasec.io/docs/pages/how-it-works/security/introduction/).
I just don't like including this "multiple levels" stuff here at all. It's an implementation detail of our framework, not an interesting selling point or salient detail. Basically, it doesn't convey anything useful to a first-time reader and we could be using this space for something better.  

If we want to say this in a more meaningful way, maybe we could say "adopted gradually" or something

2021-12-27 20:47 UTC, factoidforrest commented on docs/blog/2021-12-12-log4j-zero-day-mitigation-guide.mdx
> +data. It's designed and maintained by Cossack Labs, which also tenders it as a commercial offering.
tenders? I think this should continue to say "offers" or say "sells"

2021-12-27 20:47 UTC, factoidforrest commented on docs/blog/2021-12-14-log4j-zero-day-update-on-CVE-2021-45046.mdx
> +We could still be wrong though, so we continue to recommend that you upgrade to `2.17.0` in the event that a better
"Our reproduction could be incomplete, so we continue..."

2021-12-27 20:47 UTC, factoidforrest commented on docs/blog/2021-12-14-log4j-zero-day-update-on-CVE-2021-45046.mdx
> +We continue to recommend _not_ using `%m{nolookups}`, which we outline in our [mitigation guide](https://www.lunasec.io/docs/blog/log4j-zero-day-mitigation-guide), as we have
"as explained in our mitigation guide"

2021-12-27 20:47 UTC, factoidforrest commented on docs/blog/2021-12-14-log4j-zero-day-update-on-CVE-2021-45046.mdx
> +Log4j `2.16.0` completely mitigates this issue by removing support for message lookup patterns and disabling JNDI functionality by default. Please use `2.17.0` or newer however to mitigate other secu
`2.16.0`  has its own issues, however, so please upgrade to 2.17.0 or newer.

2021-12-27 20:47 UTC, factoidforrest commented on docs/blog/2021-12-14-log4j-zero-day-update-on-CVE-2021-45046.mdx
> +If this post helped you, please share it with others to help them too.
"please share it with others."

2021-12-27 20:52 UTC, factoidforrest commented
You're right about the confusing stuff on line 106 of the update post.  I'll fix it after this merges.

2021-12-28 17:22 UTC, aniratepanda commented on docs/blog/2021-12-12-log4j-zero-day-mitigation-guide.mdx
> +This vulnerability affects anybody who's using the log4j packages. That means that
You are right, this feels a little redundant.  This sounds kinda fucky too though, I went with an alternative that's a little more complex as a sentence but reads a little better and clearer IMO.  If you hate it I'll just revert.

2021-12-28 17:26 UTC, aniratepanda commented on docs/blog/2021-12-12-log4j-zero-day-mitigation-guide.mdx
> +- **[Overview (when to use the exploit)](https://www.lunasec.io/docs/blog/log4shell-live-patch/)**
Okay, this changes this chunk structurally, you might double check that change.

2021-12-28 17:28 UTC, aniratepanda commented on docs/blog/2021-12-12-log4j-zero-day-mitigation-guide.mdx
> +(above), and is also designed to be implemented at [multiple levels](https://www.lunasec.io/docs/pages/how-it-works/security/introduction/).
Hm.  Okay, it sounds like the person writing this was trying to make it sound like a selling point, but altered as suggested.

2021-12-28 17:31 UTC, aniratepanda commented on docs/blog/2021-12-12-log4j-zero-day-mitigation-guide.mdx
> +data. It's designed and maintained by Cossack Labs, which also tenders it as a commercial offering.
"offers as an offering" sounds weird and is redundant.   Tender means offer/sell, and sounds better than sells imo, but if you feel strongly I'll change it.

2021-12-28 17:37 UTC, aniratepanda commented on docs/blog/2021-12-14-log4j-zero-day-update-on-CVE-2021-45046.mdx
> +If this post helped you, please share it with others to help them too.
Yea, that's better. Less redundant.

2021-12-29 18:59 UTC, merged