Adding blog post talking about new CVEs and security team response
lunasec-io/lunasec pull request #390
Opened 2021-12-29 18:54 UTC by breadchris

A blog post was warranted to discuss the new CVEs and how security teams should consider them. It is too tempting to just continually update to the latest version, but understanding the cost is also important.

2021-12-30 09:10 UTC, freeqaz commented on docs/blog/2021-12-28-log4j-hype-train.mdx
> +### [12/11/21] 2.15.0 Released
I thought this was released on the 6th?

2021-12-30 09:13 UTC, freeqaz commented on docs/blog/2021-12-28-log4j-hype-train.mdx
> +We expect you to be skeptical of any claim we may make, and for that reason that is why our code is fully open source.
Open Source * is the proper spelling to convey that it's permissively licensed.

2021-12-30 09:14 UTC, freeqaz commented on docs/blog/2021-12-28-log4j-hype-train.mdx
> +truth is so are we. There is, however, an important distinction to be made. LunaSec isn't a tool which just surfaces
Could be phrased a little better but I appreciate the honesty here haha

2021-12-30 09:15 UTC, freeqaz commented on docs/blog/2021-12-28-log4j-hype-train.mdx
> +## Shameless Plug
This whole section could use a little cleanup but I like the sentiment of it.

2021-12-30 09:17 UTC, freeqaz requested changes
I'd like to tweak the copy a bit on this tomorrow. It's damn close though -- I think the structure and narrative is spot on. I just want to tighten up some of the language and help this post really shine.

2021-12-31 21:26 UTC, factoidforrest commented
@breadchris I went to town on the intro a bit, please revert it or merge into your intro if you're not a fan.  The issues I was trying to fix are:

Incomplete/confusing context around this topic.  The hook made it unclear whether we were talking about issues in 2.16 or 2.17, and had no mention of the fact that the latest 2.17 ivuln is basically BS.  So i just went ahead and said it up top.  Did my best!

Made title more descriptive while retaining meaning

Recommend people go to 2.17 instead of 2.16, it's easier than explaining the caveats around what OS people are on.  The 2.16 vuln is soooomewhat legit so I just bumped it to 2.17.0 since thats what we are recommending elsewhere in our guides.

2022-01-03 01:57 UTC, freeqaz approved these changes

2022-01-03 02:00 UTC, factoidforrest commented
Cool now just needs a few grammar/flow fixes before publish, I'll try to do it tonight or tomorrow

2022-01-03 03:47 UTC, merged