Fix a lot of small broken things
lunasec-io/lunasec pull request #590
Opened 2022-05-05 23:00 UTC by factoidforrest

2022-05-06 03:17 UTC, breadchris requested changes

2022-05-06 03:17 UTC, breadchris commented on CODEOWNERS
> +lunatrace/bsl/common @forrest
@forrest needs to be @factoidforrest

2022-05-07 00:19 UTC, factoidforrest commented on CODEOWNERS
> +lunatrace/bsl/common @forrest
thanks meng

2022-05-07 03:01 UTC, breadchris requested changes

2022-05-07 03:03 UTC, breadchris approved these changes

2022-05-09 22:11 UTC, ajvpot commented on lunatrace/bsl/frontend/src/contexts/SidebarContext.tsx
> +  const [isOpen, setIsOpen] = useState(window.innerWidth > 992);
super nit: can we use a media query for this or something?

2022-05-09 22:12 UTC, ajvpot approved these changes

2022-05-10 00:09 UTC, merged