fix guides and some ugly vuln stuff
lunasec-io/lunasec pull request #791
Opened 2022-07-21 23:49 UTC by factoidforrest

guide upserting was broken.  Need to migrate prod before merging this, i can do it.

2022-07-21 23:50 UTC, factoidforrest commented on lunatrace/bsl/hasura/migrations/lunatrace/1658439316277_fix-guides-fkey/up.sql
> +ALTER TABLE public.guide_vulnerabilities ADD COLUMN vulnerability_id uuid references vulnerability.vulnerability (id) NOT NULL;
This is the main change of this PR

2022-07-22 01:55 UTC, ajvpot commented on guides/LUNAGUIDE-20220422-1-LOG4SHELL/metadata.yaml
> +  - GHSA-jfh8-c2jp-5v3q
These are not CVEs?

2022-07-22 01:56 UTC, ajvpot requested changes
Looks good except metadata changes, if the upsert job can't handle cves in this field and resolve them we should probably make it.

2022-07-22 02:01 UTC, ajvpot approved these changes

2022-07-25 19:25 UTC, breadchris approved these changes
aside from the `cves` section on the guide that alex pointed out, looks good

2022-07-26 18:12 UTC, merged