Inserter for build dependency relationships using merkle tree
lunasec-io/lunasec pull request #846
Opened 2022-08-26 01:23 UTC by freeqaz

I still need to test this, but this is built using SQL only and I've done a basic first pass at optimizing it for speed. There is _way_ more we could do, but this should help unblock us for now.

2022-08-26 08:44 UTC, freeqaz commented on lunatrace/bsl/backend/src/snapshot/node-package-tree.ts
> +          table: 'manifest_dependency',
This line is using the helper

2022-08-26 21:40 UTC, ajvpot approved these changes

2022-08-26 22:07 UTC, factoidforrest approved these changes
nice, pretty straight forward. JW if those deleted tests are replaced with anything

2022-08-26 22:07 UTC, factoidforrest commented on lunatrace/bsl/backend/src/tests/node-package-tree.test.ts
> -      describe('root dependency counts', () => {
Are you still checking these values are correct? Is the idea of the test alive in some other check or test somewhere?  Same for any other deleted test here. Are we still doing the tests somewhere in a different way but with the same intent?

2022-08-30 00:06 UTC, ajvpot requested changes
Looks like some extraneous changes snuck in to `lunatrace/cli/cmd/log4shell/Log4ShellHotpatch.class`

2022-08-30 06:04 UTC, merged